In [1]:
from HLsearch import *
from scipy.integrate import solve_ivp
import numpy as np
from sympy import symbols, var, diff, simplify, collect,solve
from sympy.utilities.lambdify import lambdify, implemented_function

from operator import add,sub,mul

import itertools
import scipy.io as sio

import time

def generate_data(func, time, init_values):
    sol = solve_ivp(func,[time[0],time[-1]],init_values,t_eval=time, method='RK45',rtol=1e-10,atol=1e-10)
    return sol.y.T, np.array([func(0,sol.y.T[i,:]) for i in range(sol.y.T.shape[0])],dtype=np.float64)

In [67]:
print('Now start calculating Spherical Pendulum')

g = 9.81
m = 1
L = 1

def spherePend(t,y,Moment=0.0):
    theta, theta_t, phi, phi_t = y
    theta_2t,phi_2t = (-L**2*m*np.sin(theta)*np.cos(theta)*theta_t**2 + L*g*m*np.sin(theta) + L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*np.sin(phi)*np.cos(theta)*phi_t + L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*np.sin(theta)*np.cos(phi)*theta_t + L*m*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)*np.sin(phi)*np.sin(theta)*theta_t - L*m*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)*np.cos(phi)*np.cos(theta)*phi_t - L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t**2 - L*np.sin(phi)*np.sin(theta)*theta_t**2 + 2*L*np.cos(phi)*np.cos(theta)*phi_t*theta_t)*np.sin(phi)*np.cos(theta) - L*m*(-2*L*np.sin(phi)*np.cos(theta)*phi_t*theta_t - L*np.sin(theta)*np.cos(phi)*phi_t**2 - L*np.sin(theta)*np.cos(phi)*theta_t**2)*np.cos(phi)*np.cos(theta) + m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*(-2*L*np.sin(phi)*np.cos(theta)*phi_t - 2*L*np.sin(theta)*np.cos(phi)*theta_t)/2 + m*(-2*L*np.sin(phi)*np.sin(theta)*theta_t + 2*L*np.cos(phi)*np.cos(theta)*phi_t)*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)/2)/(L**2*m*np.sin(phi)**2*np.cos(theta)**2 + L**2*m*np.sin(theta)**2 + L**2*m*np.cos(phi)**2*np.cos(theta)**2),(L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*np.sin(phi)*np.cos(theta)*theta_t + L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*np.sin(theta)*np.cos(phi)*phi_t + L*m*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)*np.sin(phi)*np.sin(theta)*phi_t - L*m*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)*np.cos(phi)*np.cos(theta)*theta_t - L*m*(-L*np.sin(phi)*np.sin(theta)*phi_t**2 - L*np.sin(phi)*np.sin(theta)*theta_t**2 + 2*L*np.cos(phi)*np.cos(theta)*phi_t*theta_t)*np.sin(theta)*np.cos(phi) + L*m*(-2*L*np.sin(phi)*np.cos(theta)*phi_t*theta_t - L*np.sin(theta)*np.cos(phi)*phi_t**2 - L*np.sin(theta)*np.cos(phi)*theta_t**2)*np.sin(phi)*np.sin(theta) + Moment + m*(-2*L*np.sin(phi)*np.sin(theta)*phi_t + 2*L*np.cos(phi)*np.cos(theta)*theta_t)*(L*np.sin(phi)*np.cos(theta)*theta_t + L*np.sin(theta)*np.cos(phi)*phi_t)/2 + m*(-L*np.sin(phi)*np.sin(theta)*phi_t + L*np.cos(phi)*np.cos(theta)*theta_t)*(-2*L*np.sin(phi)*np.cos(theta)*theta_t - 2*L*np.sin(theta)*np.cos(phi)*phi_t)/2)/(L**2*m*np.sin(phi)**2*np.sin(theta)**2 + L**2*m*np.sin(theta)**2*np.cos(phi)**2)
    return theta_t,theta_2t,phi_t,phi_2t

t = np.arange(0,3,0.01)
y0=np.array([np.pi/4, 0,0, 0.5])
X,Xdot = generate_data(spherePend,t,y0)

def energy(X):
    theta, theta_t, phi, phi_t = np.hsplit(X,4)
    return L**2*m*(np.sin(theta)**2*phi_t**2 + theta_t**2 )/2 + L*m*g*np.cos(theta)

print(energy(X))

Now start calculating CartPole
[[6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6.99921752]
 [6

In [68]:
data_description = ()
for i in range(round(X.shape[1]/2)):
    data_description = data_description + symbols('x{}, x{}_t'.format(i,i))
print('Variables are:',data_description)
data_description_sym = data_description
data_description = list(str(descr) for descr in data_description)
# print(data_description_sym)
# print([data_description[i] for i in range(round(len(data_description)/2))])

expr_new0 = buildFunctionExpressions(1,round(X.shape[1]/2),[data_description[i] for i in range(round(len(data_description)/2))],use_sine=True)
expr_new1 = buildFunctionExpressions(1,round(X.shape[1]/2),[data_description[i] for i in range(round(len(data_description)/2),len(data_description))],use_sine=False)

print(expr_new0[1:])
print(expr_new1)
expr_new = expr_new0[1:]+expr_new1
expr = buildFunctionExpressions(4,len(expr_new),expr_new)
print(expr)

Variables are: (x0, x0_t, x1, x1_t)
['x0_t', 'sin(x0)', 'cos(x0)']
['x1', 'x1_t']
['x0_t', 'sin(x0)', 'cos(x0)', 'x1', 'x1_t', 'x0_t**2', 'x0_t*sin(x0)', 'sin(x0)**2', 'x0_t*cos(x0)', 'sin(x0)*cos(x0)', 'cos(x0)**2', 'x0_t*x1', 'sin(x0)*x1', 'cos(x0)*x1', 'x1**2', 'x0_t*x1_t', 'sin(x0)*x1_t', 'cos(x0)*x1_t', 'x1*x1_t', 'x1_t**2', 'x0_t**3', 'x0_t**2*sin(x0)', 'x0_t*sin(x0)**2', 'sin(x0)**3', 'x0_t**2*cos(x0)', 'x0_t*sin(x0)*cos(x0)', 'sin(x0)**2*cos(x0)', 'x0_t*cos(x0)**2', 'sin(x0)*cos(x0)**2', 'cos(x0)**3', 'x0_t**2*x1', 'x0_t*sin(x0)*x1', 'sin(x0)**2*x1', 'x0_t*cos(x0)*x1', 'sin(x0)*cos(x0)*x1', 'cos(x0)**2*x1', 'x0_t*x1**2', 'sin(x0)*x1**2', 'cos(x0)*x1**2', 'x1**3', 'x0_t**2*x1_t', 'x0_t*sin(x0)*x1_t', 'sin(x0)**2*x1_t', 'x0_t*cos(x0)*x1_t', 'sin(x0)*cos(x0)*x1_t', 'cos(x0)**2*x1_t', 'x0_t*x1*x1_t', 'sin(x0)*x1*x1_t', 'cos(x0)*x1*x1_t', 'x1**2*x1_t', 'x0_t*x1_t**2', 'sin(x0)*x1_t**2', 'cos(x0)*x1_t**2', 'x1*x1_t**2', 'x1_t**3', 'x0_t**4', 'x0_t**3*sin(x0)', 'x0_t**2*sin(x0)**2', '

In [69]:
Theta = buildTimeSerieMatrixFromFunctions(X,expr_new, data_description)
Gamma = buildTimeDerivativeMatrixFromFunctions(X,Xdot,expr    ,data_description)

In [70]:
stored_indices = ()

# print('Keeping terms: ',[expr_new[i] for i in stored_indices])
elements = tuple(x for x in range(len(expr_new)) if x not in stored_indices)

combi_number = 3
indices = itertools.combinations(elements, combi_number)

In [71]:
goodHamiltonian={}

def spherePendForce(t,y):
    return spherePend(t,y,Moment = 1.0)
    
t = np.arange(0,0.05,0.01)
y0=np.array([np.pi/4, 0,0, 0.5])
Xf,Xfdot = generate_data(spherePendForce,t,y0)

start = time.time()
for count,index in enumerate(indices):
# index_tup = (2,5,16,25)
    index_tup = index + stored_indices
#     xi_new = STRidge(Gamma_new[:,index_tup], -1*np.dot(Gamma_old,xi),0.0,1000, 10**-12, print_results=False)
#     # Hamiltonian = Hamiltonian_old+generateExpression(xi_new,[expr_new[i] for i in index_tup],threshold=1e-6)
#     Hamiltonian = generateExpression(xi_new+zero_in_xi,[expr_new[i] for i in index_tup])
    
    u, s, vh = np.linalg.svd(-Gamma[:,index_tup],full_matrices=False)

    xi = vh.T[:,-1]
    
    
    if np.linalg.norm(xi,2) < 1e-5: continue
    print(xi,[expr[i] for i in index_tup])
    Hamiltonian = generateExpression(xi,[expr[i] for i in index_tup],threshold=1e-6)
    energyFunc = lambdify(data_description,Hamiltonian,'numpy')
    energy = np.array([energyFunc(* X[i,:]) for i in range(X.shape[0])])
    if np.var(energy)<1e-3 and abs(np.mean(energy))>1e-8:
        temp_terms = [sympify(expr_new[i]) for j,i in enumerate(index_tup) if abs(xi_new[j])>1e-8]
        Lagrangian = findLagrangianFromHamiltonian(Hamiltonian,temp_terms,data_description_sym,threshold=1e-6)
        if Lagrangian is not None and Lagrangian != '':
            goodHamiltonian[simplify(Hamiltonian)] = Lagrangian
            print('Found good result at ',count,'th trial: ',index_tup)

print('Elapsed time: ',np.around(time.time()-start,2), 's')

for H,L in goodHamiltonian.items():
    print('')
    dLdq_expr = diff(L, 'x1')
    dLdqdot_expr = diff(L, 'x1_t')
    dLdq = buildTimeSerieFromFunction(Xf,dLdq_expr,data_description_sym)
    d_dLdqdot_dt = buildTimeDerivativeSerieFromFunction(Xf,Xfdot,dLdqdot_expr,data_description_sym)
    fCal = d_dLdqdot_dt-dLdq
    k = 1.0/np.mean(fCal)
    print('Hamiltonian is ',k*H)
    print('Lagrangian is ',k*L)  

[-1.31616011e-04  7.95610014e-01 -6.05809118e-01] ['x0_t', 'sin(x0)', 'cos(x0)']
[ 0.00221447 -0.99993852  0.01086509] ['x0_t', 'sin(x0)', 'x1']
[6.62375916e-04 9.99999603e-01 5.95592827e-04] ['x0_t', 'sin(x0)', 'x1_t']
[2.68592691e-04 9.99998950e-01 1.42381999e-03] ['x0_t', 'cos(x0)', 'x1']
[8.15532733e-05 9.99999995e-01 5.86548047e-05] ['x0_t', 'cos(x0)', 'x1_t']
[1.85638944e-01 9.82618019e-01 1.09323038e-04] ['x0_t', 'x1', 'x1_t']
[-7.95606772e-01  6.05813249e-01 -4.14225119e-04] ['sin(x0)', 'cos(x0)', 'x1']
[-8.15607002e-01  5.78606098e-01 -4.49459566e-04] ['sin(x0)', 'cos(x0)', 'x1_t']
[-9.99994730e-01  3.19146648e-03 -5.94948990e-04] ['sin(x0)', 'x1', 'x1_t']
[-9.99999938e-01  3.48383362e-04 -5.85403533e-05] ['cos(x0)', 'x1', 'x1_t']
Elapsed time:  0.05 s
